#!/bin/bash


git symbolic-ref HEAD refs/heads/gh-pages
rm .git/index
npm run-script generate
# or npm run-script generate
git add out/ .gitignore CNAME favicon.ico -f
git clean -fdx -e node_modules
git mv out/* .
git commit
